name: driver_app
description: Driver app (attendance + background tracking)
publish_to: "none"
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3   # optional push
  geolocator: ^13.0.1
  flutter_foreground_task: ^6.4.2   # Android foreground service
  workmanager: ^0.9.0+3              # (optional) scheduled fallback
  intl: ^0.19.0
  mobile_scanner: ^6.0.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
